import { spacingScale, type BrandTheme, type ShadowToken } from './tokens';

const shadow = (elevation: number, radius: number, opacity: number): ShadowToken => ({
  shadowColor: '#000000',
  shadowOpacity: opacity,
  shadowRadius: radius,
  shadowOffset: { width: 0, height: Math.ceil(elevation / 2) },
  elevation,
});

/** Neutral framework default. Brands override any subset via `createBrandTheme`. */
export const defaultBrandTheme: BrandTheme = {
  name: 'default',
  spacing: spacingScale,
  radii: { none: 0, sm: 4, md: 8, lg: 12, xl: 20, pill: 999 },
  fonts: {},
  typography: {
    display: { fontSize: 34, lineHeight: 41, fontWeight: '700', letterSpacing: 0.25 },
    headline: { fontSize: 24, lineHeight: 30, fontWeight: '700' },
    title: { fontSize: 20, lineHeight: 26, fontWeight: '600' },
    body: { fontSize: 16, lineHeight: 22, fontWeight: '400' },
    bodyStrong: { fontSize: 16, lineHeight: 22, fontWeight: '600' },
    label: { fontSize: 14, lineHeight: 18, fontWeight: '500', letterSpacing: 0.1 },
    caption: { fontSize: 12, lineHeight: 16, fontWeight: '400', letterSpacing: 0.2 },
  },
  elevation: {
    none: shadow(0, 0, 0),
    sm: shadow(2, 3, 0.12),
    md: shadow(4, 8, 0.16),
    lg: shadow(8, 16, 0.2),
  },
  motion: { fast: 120, normal: 200, slow: 320 },
  opacity: { disabled: 0.4, pressed: 0.7 },
  sizes: { touchTarget: 44, iconSm: 16, iconMd: 24, iconLg: 32 },
  components: {
    button: { radius: 'md', height: { sm: 36, md: 44, lg: 52 } },
    input: { radius: 'md', height: 48, borderWidth: 1 },
    card: { radius: 'lg', padding: 'lg', elevation: 'sm' },
  },
  colors: {
    light: {
      primary: '#3D5AFE',
      onPrimary: '#FFFFFF',
      primaryContainer: '#DDE1FF',
      onPrimaryContainer: '#001257',
      secondary: '#5C5F72',
      onSecondary: '#FFFFFF',
      background: '#FBFBFF',
      onBackground: '#1B1B1F',
      surface: '#FFFFFF',
      surfaceVariant: '#F1F0F7',
      onSurface: '#1B1B1F',
      onSurfaceMuted: '#5E5E6A',
      border: '#C6C5D0',
      divider: '#E4E3EC',
      danger: '#BA1A1A',
      onDanger: '#FFFFFF',
      success: '#1E7F4F',
      warning: '#8A5A00',
      info: '#0061A4',
      overlay: 'rgba(0,0,0,0.4)',
      focus: '#3D5AFE',
    },
    dark: {
      primary: '#B9C3FF',
      onPrimary: '#00228B',
      primaryContainer: '#1F3BD1',
      onPrimaryContainer: '#DDE1FF',
      secondary: '#C4C5DD',
      onSecondary: '#2D3042',
      background: '#121316',
      onBackground: '#E4E2E6',
      surface: '#1B1B1F',
      surfaceVariant: '#26262C',
      onSurface: '#E4E2E6',
      onSurfaceMuted: '#A9A8B4',
      border: '#46464F',
      divider: '#2F2F36',
      danger: '#FFB4AB',
      onDanger: '#690005',
      success: '#7DDBA3',
      warning: '#FFB951',
      info: '#9ECAFF',
      overlay: 'rgba(0,0,0,0.6)',
      focus: '#B9C3FF',
    },
  },
};
